# Generated by Django 3.2 on 2023-02-09 05:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_model',
            name='file_Date',
            field=models.DateField(default=datetime.datetime(2023, 2, 9, 5, 11, 11, 314258, tzinfo=utc), verbose_name='File data'),
        ),
    ]
