# Generated by Django 3.2 on 2023-02-16 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_file_model_file_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_model',
            name='file_Date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='File data'),
        ),
    ]
